//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerMenu.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerMenu.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the program to let the default setting to take effect..
        /// </summary>
        internal static string msgDefaultSetting {
            get {
                return ResourceManager.GetString("msgDefaultSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Menu - Users Action.
        /// </summary>
        internal static string strComment {
            get {
                return ResourceManager.GetString("strComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to hibernate the computer?.
        /// </summary>
        internal static string strConfirmHibernate {
            get {
                return ResourceManager.GetString("strConfirmHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to lock the computer?.
        /// </summary>
        internal static string strConfirmLock {
            get {
                return ResourceManager.GetString("strConfirmLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to log off from the computer?.
        /// </summary>
        internal static string strConfirmLogoff {
            get {
                return ResourceManager.GetString("strConfirmLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to reboot the computer?.
        /// </summary>
        internal static string strConfirmReboot {
            get {
                return ResourceManager.GetString("strConfirmReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to shutdown the computer?.
        /// </summary>
        internal static string strConfirmShutdown {
            get {
                return ResourceManager.GetString("strConfirmShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to sleep the computer?.
        /// </summary>
        internal static string strConfirmSleep {
            get {
                return ResourceManager.GetString("strConfirmSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string strInfoTitle {
            get {
                return ResourceManager.GetString("strInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computer is going to be restarted. Please save and close all opening files..
        /// </summary>
        internal static string strRebootComment {
            get {
                return ResourceManager.GetString("strRebootComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computer is going to be turned off. Please save and close all opening files..
        /// </summary>
        internal static string strShutdownComment {
            get {
                return ResourceManager.GetString("strShutdownComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string strWarningTitle {
            get {
                return ResourceManager.GetString("strWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show confirmation message before processing power cycle.
        /// </summary>
        internal static string tsConfirmMsg {
            get {
                return ResourceManager.GetString("tsConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibernate the computer.
        /// </summary>
        internal static string tsHibernate {
            get {
                return ResourceManager.GetString("tsHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock the computer.
        /// </summary>
        internal static string tsLock {
            get {
                return ResourceManager.GetString("tsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off from the computer.
        /// </summary>
        internal static string tsLogoff {
            get {
                return ResourceManager.GetString("tsLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot the computer.
        /// </summary>
        internal static string tsReboot {
            get {
                return ResourceManager.GetString("tsReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power off the computer.
        /// </summary>
        internal static string tsShutdown {
            get {
                return ResourceManager.GetString("tsShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep the computer.
        /// </summary>
        internal static string tsSleep {
            get {
                return ResourceManager.GetString("tsSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only support Windows Vista or above.
        /// </summary>
        internal static string tsSupportVistaAbove {
            get {
                return ResourceManager.GetString("tsSupportVistaAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set timeout before processing power cycle.
        /// </summary>
        internal static string tsTimeout {
            get {
                return ResourceManager.GetString("tsTimeout", resourceCulture);
            }
        }
    }
}
